### ISSUE TITLE
PBR textures conversion

### ISSUE THREAD

**Issue by walbourn** [walbourn/contentexporter#13]
With ``-sdkmesh2`` this tool assumes the name of the ORM, emissive, and normal name based on the diffuse texture. These are not converted to DDS because they are missing from the texture manifest.

**Comment by MattFiler** [comment]
Is there any updated documentation on SDKMESH V2? Finding it kinda tricky to work with when there's so little info!

Does it support OBJ? What MTL definitions does SDKMESH V2 look out for to locate its PBR materials?

**Comment by walbourn** [comment]
``SDKMESH`` is [this custom binary format](https://github.com/Microsoft/DirectXMesh/wiki/Geometry-formats#sdkmesh) which encodes the geometry and materials information. Generally you only need the ``SDKMESH`` and the referenced ``DDS`` textures at runtime, which is what the Sample Content Exporter exports. A full "spec" for the format is [here](https://github.com/walbourn/contentexporter/wiki/SDKMESH)

**Comment by MattFiler** [comment]
This is helpful, thanks, but I'm still confused about exactly how SDKMESH2 figures out the materials to use when converting OBJ. I'm trying to swap my pipeline from SDKMESH to the updated version so we can support the extended materials set, but having problems.

Does DirectXMesh look for MTL tags still to figure out SDKMESH2 materials, and if so, which? From what I could gather it seems to base it on file name from the first map it finds, but was unsure if this is actually the case.

**Comment by mgubisch** [comment]
for -SDKMESH2 the name of normal texture is assigned to the emissive texture leading PBR renderings look very strange if emissive texture is used
Think this line is wrong:
sdkmeshfilewriter.cpp line 152
`                ProcessTexture(Material2->EmissiveTexture, MAX_TEXTURE_NAME, pNormal->ValueString.SafeString());`

Also it would be great if the Material is set to transparent (meaning meshes using that going to alpha mesh parts on DirectXTKs input) if fbximporter detects transparency based on an alpha texture not only on the value of DiffuseColor

**Comment by walbourn** [comment]
Good catch on the first issue. It was indeed a typo. Fixed in [this commit](https://github.com/walbourn/contentexporter/commit/0e2be21c0086e319ea777f4ea258e9a495867917). As for the second issue, I'll have to think about it a bit... The problem is that the 'alpha' value is a specific number, so I'd have to assume what value to use. That said, I can understand it's not very intuitive behavior.
