### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by TokyoSU** [walbourn/contentexporter#20]
hi, i have a problem doing a convert:
if the vertices and/or polygons is 0 then the program crash without explaining anything.
it say:
```
Found existing material "name".
Found 1 UV sets.
Using 1 UV sets.
0 vertices, 0 polygons.
```
Then crash without saying what is wrong :'(
I know that this "mesh" have nothing, but if it crash, the file is not created :x 
can it be added without vertices or just ignored ?

**Comment by walbourn** [comment]
Do you have a FBX file I could use to repro the crash?

**Comment by TokyoSU** [comment]
there :)
[lara.zip](https://github.com/walbourn/contentexporter/files/7511939/lara.zip)

**Comment by walbourn** [comment]
Thanks for the repro.

If you use ``-loglevel 10`` you'll get a lot more information out of the tool. The failing sub mesh is ``LARA_HIPS_JOINT`` which is finding no verts or polygons.
 
After adding [this commit](https://github.com/walbourn/contentexporter/commit/bcf988feba467a4e93a293c2ac067f622b81e3f7) to skip 0 polygon meshes with a warning, the following are all reporting no polygons:

```
WARNING: Skipping the LARA_HIPS_JOINT mesh as it contains no polygons
WARNING: Skipping the LARA_LEFT_HIP mesh as it contains no polygons
WARNING: Skipping the LARA_LEFT_KNEE mesh as it contains no polygons
WARNING: Skipping the LARA_LEFT_ANKLE mesh as it contains no polygons
WARNING: Skipping the LARA_RIGHT_HIP mesh as it contains no polygons
WARNING: Skipping the LARA_RIGHT_KNEE mesh as it contains no polygons
WARNING: Skipping the LARA_RIGHT_ANKLE mesh as it contains no polygons
WARNING: Skipping the LARA_PELVIS mesh as it contains no polygons
WARNING: Skipping the LARA_RIGHT_SHOULDER mesh as it contains no polygons
WARNING: Skipping the LARA_RIGHT_ELBOW mesh as it contains no polygons
WARNING: Skipping the LARA_RIGHT_WRIST mesh as it contains no polygons
WARNING: Skipping the LARA_LEFT_SHOULDER mesh as it contains no polygons
WARNING: Skipping the LARA_LEFT_ELBOW mesh as it contains no polygons
WARNING: Skipping the LARA_LEFT_WRIST mesh as it contains no polygons
WARNING: Skipping the LARA_NECK mesh as it contains no polygons
```

**Comment by TokyoSU** [comment]
thank its working fine now :)
